### ISSUE TITLE
[hw2] Tail Call Optimization 구현 관련 질문

### ISSUE THREAD

**Issue by jungmin-cho-eng** [snu-sf-class/pp202202#10]
안녕하세요, 프로그래밍의 원리 수강생 조정민 입니다.

지난 hw1의 경우 Tail call optimization이 구현되어야 모든 test case를 통과할 수 있는 문제들이 있었습니다.
이번 hw2에서는 설명에 이 부분이 명시되어 있지 않은데, 이번에도 Tail call optimization을 요구하는 test case가 있을지 문의 드립니다.

감사합니다.

**Comment by MerHS** [comment]
명시적으로 tail call을 요구하는 문제는 없습니다.

다만 문제 3의 경우 Binomial heap을 제대로 구현했다면 모든 연산이 최소 O(log n) 시간에 처리될 것이지만
잘못 구현했다면 timeout이 날 수 있습니다.

이 점 고려해주시기 바랍니다.

**Comment by jungmin-cho-eng** [comment]
네 답변 주셔서 감사합니다!
