### ISSUE TITLE
과제 2 P3 BMHeap 인자 조건에 관한 질문

### ISSUE THREAD

**Issue by youngyojun** [snu-sf-class/pp202202#14]
조교님, 안녕하세요.

Problem 3. Binomial Heap 에서 구현해야 하는
네 개의 함수들 `merge`, `insert`, `findMin`, `deleteMin`의 인자로 주어지는 `BMHeap`은
* `emptyHeap = BMHeap(Nil)` 이거나
* `emptyHeap`에서 위의 네 함수를 반복적으로 적용해 얻은 값

으로 가정해도 좋을까요?

아니면, list of `BMTree`에 대해 (`BMTree` 규칙 외의) 어떠한 가정도 하지 않아야 할까요?

감사합니다.

**Comment by MerHS** [comment]
함수들에 들어가는 heap들과 출력하는 heap들은 모두 문제 정의에 적힌 Binomial Heap 조건을 만족하는 heap이어야 합니다.

값이 단 하나 들어있는 order 0 짜리 tree 하나를 가진 Singleton heap을 계속 (학생들 분이 구현한 )merge / insert를 사용해서 크기를 불린 heap이 input으로 주어진다고 보시면 됩니다.

**Comment by youngyojun** [comment]
감사합니다. 생각이 명료해졌습니다. :smile:
