### ISSUE TITLE
스칼라 버전

### ISSUE THREAD

**Issue by edcwkim** [snu-sf-class/pp202202#3]
안녕하세요.

우리 수업에서 스칼라 3을 안 사용하는 배경은 알고 있는데요.
https://github.com/snu-sf-class/pp202202/commit/0e34ff54e78d045e55e018a9b4032e3ecd7811a9 에서 버전이 2.12로 내려간 이유는 무엇인지도 여쭤볼 수 있나요? 스칼라 생태계에 대한 이해가 잘 없어서 궁금했습니다.

**Comment by MerHS** [comment]
저희 측에서 중간에 환경설정 문제로 약간 충돌이 있었습니다.

해결하였으니 scala setting pdf 대로 2.13을 다시 깔아주시면 될 것 같습니다.
