### ISSUE TITLE
[hw1] 과제 제출 시 파일명 관련 질문

### ISSUE THREAD

**Issue by peng-u-0807** [snu-sf-class/pp202202#6]
안녕하세요, 수강생 최유림입니다.
제출 서버에 `src.zip`파일을 업로드하였더니 이전에 제출 기록이 있어서 그런지 자동으로 `src` 뒤에 임의의 문자가 붙어 압축파일명이 수정되었습니다. 이러한 경우에는 제출 파일명을 어떻게 해야될까요?
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/70614553/193438442-475bc063-5d82-457e-84ec-451c7a127577.png">

**Comment by MerHS** [comment]
서버에 동일한 이름의 zip파일을 올렸을 시 중복을 피하기 위해 자동으로 이름이 변경됩니다.

zip파일 내부의 파일 이름과 디렉토리 구조만 신경쓰시면 됩니다.
